version: "3.8"

services:
  app:
    build: .
    ports:
      - "8079:8079"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/voting
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    restart: always
